- name: Check that Kibana is installed
  stat:
    path={{kibana_dir}}/bin
  register: st

- name: Download Kibana
  get_url:
    url={{kibana_download_url}}
    dest=/tmp/kibana-{{kibana_version}}-bin.tar.gz
    timeout=60
  when: not st.stat.exists

- name: Extract Kibana
  unarchive:
    src=/tmp/kibana-{{kibana_version}}-bin.tar.gz
    copy=no
    dest=/tmp
  when: not st.stat.exists

- name: Copy Kibana
  shell: cp -r /tmp/kibana-{{kibana_version}}-linux-x64 {{kibana_dir}} creates={{kibana_dir}}/bin
  when: not st.stat.exists

- name:
  lineinfile:
    dest=/home/{{user}}/.bashrc
    line='export PATH=$PATH:{{kibana_dir}}/bin'
