elasticsearch_version: 1.7.2
elasticsearch_dir: /home/{{user}}/elasticsearch-{{elasticsearch_version}}
elasticsearch_download_url: https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch-{{elasticsearch_version}}.tar.gz
