- name: Check that Zeppelin is installed
  stat:
    path={{zeppelin_dir}}/bin
  register: st

- name: Download Zeppelin
  get_url:
    url={{zeppelin_download_url}}
    dest=/tmp/zeppelin-{{zeppelin_version}}-bin-all.tgz
    timeout=60
  when: not st.stat.exists

- name: Extract Zeppelin
  unarchive:
    src=/tmp/zeppelin-{{zeppelin_version}}-bin-all.tgz
    copy=no
    dest=/tmp
  when: not st.stat.exists

- name: Copy Zeppelin
  shell: cp -r /tmp/zeppelin-{{zeppelin_version}}-bin-all {{zeppelin_dir}} creates={{zeppelin_dir}}/bin
  when: not st.stat.exists

- name: Install the init script
  template:
    src=zeppelin.sh
    dest=/etc/init.d/zeppelin
    mode=0755
  notify:
    - Register the init script
    - Restart Zeppelin
  sudo: true


- name: Create a folder for extra Jars
  file:
    path={{zeppelin_dir}}/jars
    state=directory

- name: Copy extra Jars
  get_url:
    url=http://repo1.maven.org/maven2/{{item}}
    dest={{zeppelin_dir}}/jars/
  with_items:
    - org/apache/commons/commons-csv/1.1/commons-csv-1.1.jar
    - org/scala-lang/scala-library/2.10.4/scala-library-2.10.4.jar
    - com/univocity/univocity-parsers/1.5.1/univocity-parsers-1.5.1.jar
    - com/databricks/spark-csv_2.10/1.2.0/spark-csv_2.10-1.2.0.jar

- name: Add extra Jars to the options
  template:
    src=zeppelin-env.sh
    dest={{zeppelin_dir}}/conf/zeppelin-env.sh
